### ISSUE TITLE
Model users

### ISSUE THREAD

**Issue by enlevel0** [hosannahighertech/yii2-yiiboard#10]
Hi Guys,

In MemberController.php,  'hosanna\profile\models\User' is being used. However this user.php can not be found.

How can I have this file to use class User?

Regards,
Henry

**Comment by mtangoo** [comment]
The Model comes from package https://github.com/hosannahighertech/yii2-profile
Install that module for now to be able to test. You can put your own suggestion on @DaSourcerer  's #8 if you have any
