### ISSUE TITLE
'app\assets\HighlighterAsset' can not be found

### ISSUE THREAD

**Issue by enlevel0** [hosannahighertech/yii2-yiiboard#9]
Hi Guys,

I am new and trying to play this forum module. But I had error and it complained that  'app\assets\HighlighterAsset' not found.

Environment:
- windows7
- yii2

Did I miss some dependency module? But all that are mentioined in composer.json are already there.

  "require": {
    "php": ">=5.4.0",
    "yiisoft/yii2": "_",
    "yiisoft/yii2-bootstrap": "_",
    "yiisoft/yii2-swiftmailer": "_"
  },
  "require-dev": {
    "yiisoft/yii2-codeception": "_",
    "yiisoft/yii2-debug": "_",
    "yiisoft/yii2-gii": "_",
    "yiisoft/yii2-faker": "*"
  }

Can you please advise?

Thanks & Regards,
Henry

**Comment by mtangoo** [comment]
Hi @enlevel0,
this is a bug to the module. The Module was dependant on Application wide asset that is not included in the module. Am going to fix it today.
Thanks for reporting

**Comment by mtangoo** [comment]
Please confirm that the issue is gone before I close the ticket

**Comment by enlevel0** [comment]
it is confirmed that it is fixed now
